using System.Collections.Generic;

namespace Virtual_Piano.Notes
{
    public static class MidiPercussionNoteFactory
    {

        public static IReadOnlyDictionary<MidiPercussionNoteCategory, IEnumerable<MidiPercussionNote>> Instance = new Dictionary<MidiPercussionNoteCategory, IEnumerable<MidiPercussionNote>>
        {
            [MidiPercussionNoteCategory.Cymbal] = new MidiPercussionNote[]
            {
                 MidiPercussionNote.CrashCymbal1,
                 MidiPercussionNote.RideCymbal1,
                 MidiPercussionNote.ChinaCymbal,
                 MidiPercussionNote.SplashCymbal,
                 MidiPercussionNote.CrashCymbal2,
                 MidiPercussionNote.RideCymbal2,
            },
            [MidiPercussionNoteCategory.Hat] = new MidiPercussionNote[]
            {
                 MidiPercussionNote.ClosedHiHat,
                 MidiPercussionNote.PedalHiHat,
                 MidiPercussionNote.OpenHiHat,
            },
            [MidiPercussionNoteCategory.Drum] = new MidiPercussionNote[]
            {
                 MidiPercussionNote.AcousticBassDrum,
                 MidiPercussionNote.BassDrum1,
                 MidiPercussionNote.SideStickRimShot,
                 MidiPercussionNote.AcousticSnareDrum,
                 MidiPercussionNote.ElectricSnareDrum,
            },
            [MidiPercussionNoteCategory.Tom] = new MidiPercussionNote[]
            {
                 MidiPercussionNote.LowFloorTom,
                 MidiPercussionNote.HighFloorTom,
                 MidiPercussionNote.LowTom,
                 MidiPercussionNote.LowLowMidTom,
                 MidiPercussionNote.HighMidTom,
                 MidiPercussionNote.HighTom,
            },
            [MidiPercussionNoteCategory.Ethnic] = new MidiPercussionNote[]
            {
                 MidiPercussionNote.HighBongo,
                 MidiPercussionNote.LowBongo,
                 MidiPercussionNote.MuteHighConga,
                 MidiPercussionNote.HighConga,
                 MidiPercussionNote.LowConga,
                 MidiPercussionNote.HighTimbale,
                 MidiPercussionNote.LowTimbale,
                 MidiPercussionNote.HighAgogo,
                 MidiPercussionNote.LowAgogo,
                 MidiPercussionNote.Cabasa,
                 MidiPercussionNote.Maracas,
                 MidiPercussionNote.ShortHighWhistle,
                 MidiPercussionNote.LongLowWhistle,
                 MidiPercussionNote.ShortHighGuiro,
                 MidiPercussionNote.LongLowGuiro,
                 MidiPercussionNote.HighWoodblock,
                 MidiPercussionNote.LowWoodblock,
                 MidiPercussionNote.MuteCuica,
                 MidiPercussionNote.OpenCuica,
                 MidiPercussionNote.MuteTriangle,
                 MidiPercussionNote.OpenTriangle,
                 MidiPercussionNote.MuteSurdo,
                 MidiPercussionNote.OpenSurdo,
            },
            [MidiPercussionNoteCategory.Synth] = new MidiPercussionNote[]
            {
                 MidiPercussionNote.HighQ,
                 MidiPercussionNote.Slap,
                 MidiPercussionNote.ScratchPush,
                 MidiPercussionNote.ScratchPull,
            },
            [MidiPercussionNoteCategory.Special] = new MidiPercussionNote[]
            {
                 MidiPercussionNote.Sticks,
                 MidiPercussionNote.SquareClick,
                 MidiPercussionNote.MetronomeClick,
                 MidiPercussionNote.MetronomeBell,
                 MidiPercussionNote.HandClap,
                 MidiPercussionNote.RideBell,
                 MidiPercussionNote.Tambourine,
                 MidiPercussionNote.Cowbell,
                 MidiPercussionNote.VibratoSlap,
                 MidiPercussionNote.Claves,
                 MidiPercussionNote.Shaker,
                 MidiPercussionNote.SleighBells,
                 MidiPercussionNote.BellTree,
                 MidiPercussionNote.Castanets,
            },
        };

        public static IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
        {
            [MidiPercussionNoteCategory.Cymbal.ToString()] = "Cymbal",
            [MidiPercussionNoteCategory.Hat.ToString()] = "Hat",
            [MidiPercussionNoteCategory.Drum.ToString()] = "Drum",
            [MidiPercussionNoteCategory.Tom.ToString()] = "Tom",
            [MidiPercussionNoteCategory.Ethnic.ToString()] = "Ethnic",
            [MidiPercussionNoteCategory.Synth.ToString()] = "Synth",
            [MidiPercussionNoteCategory.Special.ToString()] = "Special",


            [MidiPercussionNote.CrashCymbal1.ToString()] = "Crash Cymbal 1",
            [MidiPercussionNote.RideCymbal1.ToString()] = "Ride Cymbal 1",
            [MidiPercussionNote.ChinaCymbal.ToString()] = "China Cymbal",
            [MidiPercussionNote.SplashCymbal.ToString()] = "Splash Cymbal",
            [MidiPercussionNote.CrashCymbal2.ToString()] = "Crash Cymbal 2",
            [MidiPercussionNote.RideCymbal2.ToString()] = "Ride Cymbal 2",
            [MidiPercussionNote.ClosedHiHat.ToString()] = "Closed Hi-Hat",
            [MidiPercussionNote.PedalHiHat.ToString()] = "Pedal Hi-Hat",
            [MidiPercussionNote.OpenHiHat.ToString()] = "Open Hi-Hat",
            [MidiPercussionNote.AcousticBassDrum.ToString()] = "Acoustic Bass Drum",
            [MidiPercussionNote.BassDrum1.ToString()] = "Bass Drum 1",
            [MidiPercussionNote.SideStickRimShot.ToString()] = "Side Stick/Rim Shot",
            [MidiPercussionNote.AcousticSnareDrum.ToString()] = "Acoustic Snare Drum",
            [MidiPercussionNote.ElectricSnareDrum.ToString()] = "Electric Snare Drum",
            [MidiPercussionNote.LowFloorTom.ToString()] = "Low Floor Tom",
            [MidiPercussionNote.HighFloorTom.ToString()] = "High Floor Tom",
            [MidiPercussionNote.LowTom.ToString()] = "Low Tom",
            [MidiPercussionNote.LowLowMidTom.ToString()] = "Low-LowMid Tom",
            [MidiPercussionNote.HighMidTom.ToString()] = "HighMid Tom",
            [MidiPercussionNote.HighTom.ToString()] = "High Tom",
            [MidiPercussionNote.HighQ.ToString()] = "High Q",
            [MidiPercussionNote.Slap.ToString()] = "Slap",
            [MidiPercussionNote.ScratchPush.ToString()] = "Scratch Push",
            [MidiPercussionNote.ScratchPull.ToString()] = "Scratch Pull",
            [MidiPercussionNote.HighBongo.ToString()] = "High Bongo",
            [MidiPercussionNote.LowBongo.ToString()] = "Low Bongo",
            [MidiPercussionNote.MuteHighConga.ToString()] = "Mute High Conga",
            [MidiPercussionNote.HighConga.ToString()] = "High Conga",
            [MidiPercussionNote.LowConga.ToString()] = "Low Conga",
            [MidiPercussionNote.HighTimbale.ToString()] = "High Timbale",
            [MidiPercussionNote.LowTimbale.ToString()] = "Low Timbale",
            [MidiPercussionNote.HighAgogo.ToString()] = "High Agogo",
            [MidiPercussionNote.LowAgogo.ToString()] = "Low Agogo",
            [MidiPercussionNote.Cabasa.ToString()] = "Cabasa",
            [MidiPercussionNote.Maracas.ToString()] = "Maracas",
            [MidiPercussionNote.ShortHighWhistle.ToString()] = "Short High Whistle",
            [MidiPercussionNote.LongLowWhistle.ToString()] = "Long Low Whistle",
            [MidiPercussionNote.ShortHighGuiro.ToString()] = "Short High Guiro",
            [MidiPercussionNote.LongLowGuiro.ToString()] = "Long Low Guiro",
            [MidiPercussionNote.HighWoodblock.ToString()] = "High Woodblock",
            [MidiPercussionNote.LowWoodblock.ToString()] = "Low Woodblock",
            [MidiPercussionNote.MuteCuica.ToString()] = "Mute Cuica",
            [MidiPercussionNote.OpenCuica.ToString()] = "Open Cuica",
            [MidiPercussionNote.MuteTriangle.ToString()] = "Mute Triangle",
            [MidiPercussionNote.OpenTriangle.ToString()] = "Open Triangle",
            [MidiPercussionNote.MuteSurdo.ToString()] = "Mute Surdo",
            [MidiPercussionNote.OpenSurdo.ToString()] = "Open Surdo",
            [MidiPercussionNote.Sticks.ToString()] = "Sticks",
            [MidiPercussionNote.SquareClick.ToString()] = "Square Click",
            [MidiPercussionNote.MetronomeClick.ToString()] = "Metronome Click",
            [MidiPercussionNote.MetronomeBell.ToString()] = "Metronome Bell",
            [MidiPercussionNote.HandClap.ToString()] = "Hand Clap",
            [MidiPercussionNote.RideBell.ToString()] = "Ride Bell",
            [MidiPercussionNote.Tambourine.ToString()] = "Tambourine",
            [MidiPercussionNote.Cowbell.ToString()] = "Cowbell",
            [MidiPercussionNote.VibratoSlap.ToString()] = "Vibrato Slap",
            [MidiPercussionNote.Claves.ToString()] = "Claves",
            [MidiPercussionNote.Shaker.ToString()] = "Shaker",
            [MidiPercussionNote.SleighBells.ToString()] = "Sleigh Bells",
            [MidiPercussionNote.BellTree.ToString()] = "Bell Tree",
            [MidiPercussionNote.Castanets.ToString()] = "Casta nets",

        };

        public static IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
        {
            [MidiPercussionNoteCategory.Cymbal.ToString()] = "铜钹",
            [MidiPercussionNoteCategory.Hat.ToString()] = "钹",
            [MidiPercussionNoteCategory.Drum.ToString()] = "小鼓",
            [MidiPercussionNoteCategory.Tom.ToString()] = "鼓",
            [MidiPercussionNoteCategory.Ethnic.ToString()] = "民族乐器",
            [MidiPercussionNoteCategory.Synth.ToString()] = "合成",
            [MidiPercussionNoteCategory.Special.ToString()] = "特殊",


            [MidiPercussionNote.CrashCymbal1.ToString()] = "铜钹 1",
            [MidiPercussionNote.RideCymbal1.ToString()] = "高架钹",
            [MidiPercussionNote.ChinaCymbal.ToString()] = "中国铜钹",
            [MidiPercussionNote.SplashCymbal.ToString()] = "溅开钹声",
            [MidiPercussionNote.CrashCymbal2.ToString()] = "铜钹 2",
            [MidiPercussionNote.RideCymbal2.ToString()] = "高架钹 2",
            [MidiPercussionNote.ClosedHiHat.ToString()] = "闭合双面钹",
            [MidiPercussionNote.PedalHiHat.ToString()] = "踏板双面钹",
            [MidiPercussionNote.OpenHiHat.ToString()] = "开放双面钹",
            [MidiPercussionNote.AcousticBassDrum.ToString()] = "低音大鼓",
            [MidiPercussionNote.BassDrum1.ToString()] = "低音鼓",
            [MidiPercussionNote.SideStickRimShot.ToString()] = "鼓边敲击",
            [MidiPercussionNote.AcousticSnareDrum.ToString()] = "小鼓",
            [MidiPercussionNote.ElectricSnareDrum.ToString()] = "电子小鼓",
            [MidiPercussionNote.LowFloorTom.ToString()] = "落地中音鼓-低音",
            [MidiPercussionNote.HighFloorTom.ToString()] = "落地中音鼓-高音",
            [MidiPercussionNote.LowTom.ToString()] = "中音鼓-低音",
            [MidiPercussionNote.LowLowMidTom.ToString()] = "中音鼓-中低音",
            [MidiPercussionNote.HighMidTom.ToString()] = "中音鼓-中高音",
            [MidiPercussionNote.HighTom.ToString()] = "高音鼓-高音",
            [MidiPercussionNote.HighQ.ToString()] = "激光枪声",
            [MidiPercussionNote.Slap.ToString()] = "合成拍音",
            [MidiPercussionNote.ScratchPush.ToString()] = "高音刷音",
            [MidiPercussionNote.ScratchPull.ToString()] = "低音刷音",
            [MidiPercussionNote.HighBongo.ToString()] = "南美小鼓-高音",
            [MidiPercussionNote.LowBongo.ToString()] = "南美小鼓-低音",
            [MidiPercussionNote.MuteHighConga.ToString()] = "康加鼓-闷高音",
            [MidiPercussionNote.HighConga.ToString()] = "康加鼓-开高音",
            [MidiPercussionNote.LowConga.ToString()] = "康加鼓-低音",
            [MidiPercussionNote.HighTimbale.ToString()] = "定音鼓-高音",
            [MidiPercussionNote.LowTimbale.ToString()] = "定音鼓-低音",
            [MidiPercussionNote.HighAgogo.ToString()] = "阿哥哥-高音",
            [MidiPercussionNote.LowAgogo.ToString()] = "阿哥哥-低音",
            [MidiPercussionNote.Cabasa.ToString()] = "抓筒",
            [MidiPercussionNote.Maracas.ToString()] = "响葫芦",
            [MidiPercussionNote.ShortHighWhistle.ToString()] = "短口哨",
            [MidiPercussionNote.LongLowWhistle.ToString()] = "长口哨",
            [MidiPercussionNote.ShortHighGuiro.ToString()] = "短梗笛",
            [MidiPercussionNote.LongLowGuiro.ToString()] = "长梗笛",
            [MidiPercussionNote.HighWoodblock.ToString()] = "木鱼-高音",
            [MidiPercussionNote.LowWoodblock.ToString()] = "木鱼-低音",
            [MidiPercussionNote.MuteCuica.ToString()] = "木笛-闷音",
            [MidiPercussionNote.OpenCuica.ToString()] = "木笛-开音",
            [MidiPercussionNote.MuteTriangle.ToString()] = "三角铃-闷音",
            [MidiPercussionNote.OpenTriangle.ToString()] = "三角铃-开音",
            [MidiPercussionNote.MuteSurdo.ToString()] = "弱音瑟多",
            [MidiPercussionNote.OpenSurdo.ToString()] = "空心瑟多",
            [MidiPercussionNote.Sticks.ToString()] = "鼓槌",
            [MidiPercussionNote.SquareClick.ToString()] = "敲方板",
            [MidiPercussionNote.MetronomeClick.ToString()] = "节拍器",
            [MidiPercussionNote.MetronomeBell.ToString()] = "节拍器重音",
            [MidiPercussionNote.HandClap.ToString()] = "拍掌",
            [MidiPercussionNote.RideBell.ToString()] = "悬挂钟",
            [MidiPercussionNote.Tambourine.ToString()] = "摇鼓",
            [MidiPercussionNote.Cowbell.ToString()] = "牛铃",
            [MidiPercussionNote.VibratoSlap.ToString()] = "颤击",
            [MidiPercussionNote.Claves.ToString()] = "响鞭",
            [MidiPercussionNote.Shaker.ToString()] = "高沙锤",
            [MidiPercussionNote.SleighBells.ToString()] = "铃铛",
            [MidiPercussionNote.BellTree.ToString()] = "铃树",
            [MidiPercussionNote.Castanets.ToString()] = "响板",
        };

    }
}