namespace Virtual_Piano.Notes
{
    public enum MidiPercussionNote : byte
    {
        HighQ = 27,
        Slap = 28,
        ScratchPush = 29,
        ScratchPull = 30,
        Sticks = 31,
        SquareClick = 32,
        MetronomeClick = 33,
        MetronomeBell = 34,
        AcousticBassDrum = 35,
        BassDrum1 = 36,
        SideStickRimShot = 37,
        AcousticSnareDrum = 38,
        HandClap = 39,
        ElectricSnareDrum = 40,
        LowFloorTom = 41,
        ClosedHiHat = 42,
        HighFloorTom = 43,
        PedalHiHat = 44,
        LowTom = 45,
        OpenHiHat = 46,
        LowLowMidTom = 47,
        HighMidTom = 48,
        CrashCymbal1 = 49,
        HighTom = 50,
        RideCymbal1 = 51,
        ChinaCymbal = 52,
        RideBell = 53,
        Tambourine = 54,
        SplashCymbal = 55,
        Cowbell = 56,
        CrashCymbal2 = 57,
        VibratoSlap = 58,
        RideCymbal2 = 59,
        HighBongo = 60,
        LowBongo = 61,
        MuteHighConga = 62,
        HighConga = 63,
        LowConga = 64,
        HighTimbale = 65,
        LowTimbale = 66,
        HighAgogo = 67,
        LowAgogo = 68,
        Cabasa = 69,
        Maracas = 70,
        ShortHighWhistle = 71,
        LongLowWhistle = 72,
        ShortHighGuiro = 73,
        LongLowGuiro = 74,
        Claves = 75,
        HighWoodblock = 76,
        LowWoodblock = 77,
        MuteCuica = 78,
        OpenCuica = 79,
        MuteTriangle = 80,
        OpenTriangle = 81,
        Shaker = 82,
        SleighBells = 83,
        BellTree = 84,
        Castanets = 85,
        MuteSurdo = 86,
        OpenSurdo = 87,
    }
}